#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SportMeet.Resource", IsApplication=true)]

namespace SportMeet
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fade_in = 2130968576;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060001
			public const int theme_material_light_noactionbar_fullscreen_background = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int theme_sportmeet_background = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int RegistrationSuccessful = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080006
			public const int ButtonLogin = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int ButtonRegister = 2131230727;
			
			// aapt resource value: 0x7f080010
			public const int ButtonRegisterCancel = 2131230736;
			
			// aapt resource value: 0x7f08000f
			public const int ButtonRegisterConfirm = 2131230735;
			
			// aapt resource value: 0x7f080005
			public const int CbRememberLogin = 2131230725;
			
			// aapt resource value: 0x7f080001
			public const int ImageRegistrationSuccessful = 2131230721;
			
			// aapt resource value: 0x7f080004
			public const int TextPassword = 2131230724;
			
			// aapt resource value: 0x7f08000a
			public const int TextRegisterEmail = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int TextRegisterFirstName = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int TextRegisterLastName = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int TextRegisterPasswordOne = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int TextRegisterPasswordTwo = 2131230734;
			
			// aapt resource value: 0x7f080009
			public const int TextRegisterUsername = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int TextRegistrationFailed = 2131230728;
			
			// aapt resource value: 0x7f080002
			public const int TextRegistrationSuccessful = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int TextUsername = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int linearLayout1 = 2131230720;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Register = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_SportMeet = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
