#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SportMeet.Resource", IsApplication=true)]

namespace SportMeet
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050001
			public const int theme_material_light_noactionbar_fullscreen_background = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int theme_sportmeet_background = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070003
			public const int ButtonLogin = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int ButtonRegister = 2131165188;
			
			// aapt resource value: 0x7f07000c
			public const int ButtonRegisterCancel = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int ButtonRegisterConfirm = 2131165195;
			
			// aapt resource value: 0x7f070002
			public const int TextPassword = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int TextRegisterEmail = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int TextRegisterFirstName = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int TextRegisterLastName = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int TextRegisterPasswordOne = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int TextRegisterPasswordTwo = 2131165194;
			
			// aapt resource value: 0x7f070005
			public const int TextRegisterUsername = 2131165189;
			
			// aapt resource value: 0x7f070001
			public const int TextUsername = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Register = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_SportMeet = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
